---
- name: install packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc-c++
    - glibc-headers
    - openssl-devel
    - readline
    - libyaml-devel
    - readline-devel
    - zlib
    - zlib-devel

- name: install mariaDB
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mariadb
    - mariadb-server

- name: install git
  yum:
    name: git
    state: present

- name: install rbenv
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: ~/.rbenv
